{% set name = "pyeviews" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8a1ee00c1ba7da7b267b5a0607d877d7ba3ecf02a4616059ac0b836e301c750a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pandas
    - pip
    - python
    - pywin32-ctypes
  run:
    - numpy
    - pandas
    - python
    - pywin32-ctypes

test:
  imports:
    - pyeviews

about:
  home: "https://github.com/bexer/pyeviews"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Data import/export and EViews function calls from Python"
  doc_url: 
  dev_url: 

app:
  summary: "Data import/export and EViews function calls from Python"
  
extra:
  recipe-maintainers:
    - bexer
