travis:
  secure:
    BINSTAR_TOKEN: KhPOgBz1oFTiy88Q9h6+0wMhHyuh2/6neH1fz5bnx70F8PKLGbRuB63oK7UwwtePmmNPR/fRiTg0R66NyTLiBo49jpTxKa/qzxGxY5Tt9y066J0TjApZzOY2zv8rnxux5JbdjHJgFLxMJcSVJmcK94teWs3B17z+CmIMjsyr4e8hoFpFMa3g6WMTkvqaWq2V4tJYJ2ic6QNx+nJ2u35pO+yFULSzIVnmR1ewRawR8dTUwYkc9BbuH4kELXV8itGWqP3q2/BO0xbQtKL0c5JTchi0oyk+aDC3J9fAF5vAd1dZfxnR59ckahOp+KAV9huNITsazRyQ1JWP0llkBDsASYmizmjmifhF8DcHzJPJbB8e5JnGQX8s2MyXOiXa49bXEHeuih58dy1Wizm7jgjE41n891OuTHTI7Sd4X/5p09gmHvwbHifDG/yiqsjwAI7B6m1YjcRdJ7SGZllJw815L1JRUoNr3WMtoOT6oQjM8wonV2jtKi1FrjbONiezxb6tJJNJ32o8OB4q6UY/9RYKKXEh44J8cC8oHymPvZsELJCxbiek+qRwv0DKb58TZobM1ez3f6S2YIopD39oNl5GlNgy3t+LiPQnd3VAdl6ic7HzPJahLste1xfMzkni6MgoKNOVk16vDwUNeiWXkoamoDpv99phsNO1++jeKLPmupE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
